import type { Metadata } from "next";

export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://stonebritecg.com";
export const SITE_NAME = "Stonebrite Construction Group";

/**
 * Sitewide share image, generated by src/app/opengraph-image.tsx. The
 * file-based image is only attached automatically to pages that inherit the
 * root layout's `openGraph`; any page that sets its own must list it.
 */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Stonebrite Construction Group — Bathroom & Kitchen Remodeling",
};

type PageMeta = {
  /** Short page title; the site name suffix is added automatically. */
  title: string;
  description: string;
  /** Path of the page, e.g. "/bathrooms". Used for canonical + og:url. */
  path: string;
  keywords?: string;
  /** Set for pages that should stay out of search (thank-you, login). */
  noindex?: boolean;
};

/**
 * Per-page metadata. Next.js replaces nested objects like `openGraph`
 * wholesale (no deep merge), so each page must supply the full set. Without
 * this every page inherited the root layout's canonical + og:url and told
 * search engines and social previews it was the homepage.
 */
export function pageMetadata({
  title,
  description,
  path,
  keywords,
  noindex,
}: PageMeta): Metadata {
  const fullTitle = `${title} | ${SITE_NAME}`;
  // Match how Next resolves canonicals: apex with no trailing slash.
  const url = new URL(path, SITE_URL).toString().replace(/\/$/, "");

  return {
    title,
    description,
    ...(keywords ? { keywords } : {}),
    ...(noindex ? { robots: { index: false, follow: false } } : {}),
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_US",
      url,
      title: fullTitle,
      description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [OG_IMAGE],
    },
  };
}
